### ISSUE TITLE
Fail the action on misconfiguration

### ISSUE THREAD

**Issue by shashankkr** [Azure/deploy#176]
I have 2 steps in my workflow 

```
- name: What If
        uses: azure/bicep-deploy@v2
        continue-on-error: false
        with:
          type: deployment
          scope: subscription
          subscription-id: ${{ inputs.azureSubscriptionId }}
          location: ${{ inputs.azureLocation }}
          name: ${{ env.deploymentName }}
          operation: whatIf
          template-file: ${{ env.bicep }}
          parameters-file: ${{ env.bicepParam }} 
          parameters: '{"environment":"${{ inputs.environment }}"'

- name: Validate Deployment
        uses: azure/bicep-deploy@v2
        if: ${{ inputs.basysId != null }}
        continue-on-error: false
        with:
          type: deployment
          scope: subscription
          subscription-id: ${{ inputs.azureSubscriptionId }}
          location: ${{ inputs.azureLocation }}
          name: ${{ env.deploymentName }}
          operation: validate
          template-file: ${{ env.bicep }}
          parameters-file: ${{ env.bicepParam }} 
         parameters: '{"environment":"${{ inputs.environment }}"'
```

If there is some task config error like not supplying the right number of parameters, both the steps succeed. 

Expected behavior, step should exit 1, means the workflow should terminate with error. 

![Image](https://github.com/user-attachments/assets/83fead05-c579-42df-b2d3-4f2e16239229)
